### ISSUE TITLE
not py expert try py, sorry, some msg in log

### ISSUE THREAD

**Issue by pflegende** [ReinhardZeiser/JupyterCodeParser#1]
Python 3.8.10 is running.

Sorry, Im not a py expert. 
But your tool comes exactly to the point I need.
So I give my python experience a try.

Seems, it is only a using fault. I hope so.

# What happens:
1. automated cloning your repo, seems ok
2. dl my ipynb from gh; seems ok - also (dl:299k)
3. was looking around the cloned repo
4. ... and I try it: python3 JupyterCodeParser/parse_ipynb.py BI.ipynb
5. but it fails with something like "JSONDecodeError: Expecting value: line 7 column 1 (char 6)"

## ... 1. and 2.:

```
~/JupyterCodeParser-1$ ls
JupyterCodeParser  requirements.txt
README.md
~/JupyterCodeParser-1$ curl -o BI.ipynb https://github.com/pflegende/BetteninventurTH/blob/master/BetteninventurThur-CountCat2ixio.ipynb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0 100  116k    0  116k    0     0   299k      0 --:--:-- --:--:-- --:--:--  299k
```
(this was part 1 and 2)

## 3. looking around
now some exploration of the cloned environment
only for overview:

```
~/JupyterCodeParser-1$ ls              
BI.ipynb       README.md               
JupyterCodeParser  requirements.txt    

~/JupyterCodeParser-1$ cd JupyterCodeParser/
~/JupyterCodeParser-1/JupyterCodeParser$ ls
__init__.py run_ipynb.py parse_ipynb.py

~/JupyterCodeParser-1/JupyterCodeParser$ cd ~
~$ ls
JupyterCodeParser-1  _test_runner.py
~$ cd JupyterCodeParser-1/
~/JupyterCodeParser-1$ ls              
BI.ipynb       README.md
JupyterCodeParser  requirements.txt
```

## part 4 begins and fails (part 5):

```
~/JupyterCodeParser-1$ python3 JupyterCodeParser/parse_ipynb.py BI.ipynb
Traceback (most recent call last):
  File "JupyterCodeParser/parse_ipynb.py", line 71, in <module>
    parse(ipynb_path, outputfile)
  File "JupyterCodeParser/parse_ipynb.py", line 34, in parse
    ipynb = json.load(f)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 6)
~/JupyterCodeParser-1$ 
```

Would be nice to have some hint where to begin my python - research 
;)

CU

**Comment by pflegende** [comment]
Oh, Im sorry:
had touched too quickly the gh file, but not the right on.
https://raw.githubusercontent.com/pflegende/BetteninventurTH/master/BetteninventurThur-CountCat2ixio.ipynb

... the littel "raw" helped many!

Im sorry for your inconvenience.
